name: CI workflow
on:
  push:
    - main
  pull_request:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt